"""add new fields error, phase, rssi, ph_level to data

Revision ID: 6a9db0eab1c8
Revises: b381ec69251f
Create Date: 2025-12-18 22:44:29.513085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9db0eab1c8'
down_revision = 'b381ec69251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('error', sa.String(length=255), nullable=True))
    op.add_column('data', sa.Column('phase', sa.String(length=255), nullable=True))
    op.add_column('data', sa.Column('rssi', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('ph_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'ph_level')
    op.drop_column('data', 'rssi')
    op.drop_column('data', 'phase')
    op.drop_column('data', 'error')
    # ### end Alembic commands ###
